### ISSUE TITLE
Prototype Router supports HL7

### ISSUE THREAD

**Issue by RickHawesUSDS** [CDCgov/prime-data-hub#10]
**Story**
As a PHD, I would like to receive messages in the HL7 format. As a prototype user, I would like to see this capability in action. 

**Assumptions**
- HL7 2.5.1
- The prototype will not hit a real HL7 end-point

**Tasks**
- [x] FHS, BHS
- [x] MSH
- [x] SFT
- [x] ORC
- [ ] OBX
- [ ] OBX for AOE
- [ ] SPM
- [ ] NTE 

**Acceptance Criteria**
- Each data element from the message is present in the HL7
- The HL7 message can verified by a tool like https://hl7inspector.com/

**Comment by drew-usds** [comment]
- [ ] @drew-usds @jlusds Find HL7 implementation guide
