### ISSUE TITLE
Translate test device to test type field

### ISSUE THREAD

**Issue by jlusds** [CDCgov/prime-data-hub#100]
Ask from Pima county: Be able to map a device type to test type

Eg. BinaxNOW™ COVID-19 Ag Card  = Antigen

**Comment by jimduff-usds** [comment]
@jlusds  - this is listed as a blocker for the Pima Schema.   Is that still the case?

I think the official table of devices is the LIVD xlsx table (https://www.cdc.gov/csels/dls/sars-cov-2-livd-codes.html), which lists "BinaxNOW COVID-19 Ag Card" as a device Model (its on row 16)    Can you tell us what other value in row 16 you want to display?

**Comment by jlusds** [comment]
Yes, this was a request from Pima. They want the device type translated to test type (Antigen, PCR)
