### ISSUE TITLE
The json response to a POST to api/reports should include the 'topic' field.

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-data-hub#1007]
Add the topic to the json response to api/reports

This is DONE when:
[ ] topic is added as a top-level value in the json response we send back from a submission to api/reports.  Its ok to have it there when the submission fails.
[ ] Re-run ./prime test  locally, to insure this didn't break anything.  This takes 5 minutes or so, to run.
[ ] Update docs/openapi.yml .  It may be out of date in other ways too. update as needed.
[ ] Since this is a customer facing change, we'll need to provide notification prior to production deployment.

**Comment by tlosbo** [comment]
I'll take this one. I don't think we can assign it to ourselves though?

**Comment by jimduff-usds** [comment]
> I'll take this one. I don't think we can assign it to ourselves though?

Consider it yours!    Best I can do at the moment is assign it to Joe.

**Comment by jimduff-usds** [comment]
@tlosbo  - this is done?

**Comment by tlosbo** [comment]
This is done with PR #1031 merged in.
