### ISSUE TITLE
Add ability to send a tiny test file to the check/sftpcheck Azure Function

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-data-hub#1008]
CheckFunction is designed to help us diagnose problems with the system.   Right now it only checks one thing:  sftp connections too states.

It is meant to be run manually, with postman or curl, ad-hoc, as we on-board states, and as we detect problems.  So, its a diagnostic tool.

This task is DONE when:

[ ] the sftp check has a new optional way to send a file.  this should be implemented as an http parameter, eg `&sendfile`.   The file should be sent as the content body of the sftp check call, just like we do for reports.   For example the payload could be specified like this to a. curl call --data-binary "@/my/test/file.txt"
[ ] if the file is over a certain size, fail.  Only allow small files (???)
[ ] The current way of running sftp check work exactly as it does not, if the new file option is not included.

**Comment by jimduff-usds** [comment]
@tlosbo has this one.

**Comment by MauriceReeves-usds** [comment]
It might also be good to allow the check to just write an empty `helloworld.txt` file if we specify that as an option.  This should also probably be rate-limited so that someone cannot post many of these and DDoS a state or us.

**Comment by tlosbo** [comment]
Would you setup the rate limiting in Azure as part of some WAF controls? Or were you thinking of implementing rate limiting in the application code?

**Comment by tlosbo** [comment]
@jimduff-usds @MauriceReeves-usds 
I have some thoughts / questions on this ticket. The current end point is a GET end point. I'll need to make it a POST as well to allow for an uploaded file on the SFTP check. Thinking through options here's what I have in mind:
* Allow for the new optional sendfile parameter and honor GET/POST. If it is a GET request then use a zero byte helloworld.txt file as @MauriceReeves-usds mentioned in the comment above.
* Create a new POST end point and move the common code into supporting functions in the class containing two distinct end point functions

Keeping as one might make it a bit easier and using the GET with the generic helloworld.txt for simple quick checks. And the POST could be used to test a specific file for troubleshooting.

**Comment by jimduff-usds** [comment]
I'd keep this really simple - its a small endpoint.  Why not only have the POST, and get rid of the GET?

**Comment by tlosbo** [comment]
I'm running all the tests and submitting a PR right now. I ended up keeping it in the same endpoint and conditionally upload the file based on how it is called.

**Comment by MauriceReeves-usds** [comment]
@jimduff-usds we merged in #1115. We can probably put this into Review/QA if not done. Agreed?

**Comment by tlosbo** [comment]
Had forgotten to assign this to myself. Since it has been merged, do I close the ticket or will someone else move it along to Review/QA?

**Comment by tlosbo** [comment]
Can we close this or is further review needed.
