### ISSUE TITLE
MS Dynamics testing & transition

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-data-hub#1017]
Dynamics will be moved to "production" potentially as soon as 4/10, but we'll need to do a lot to make sure the state intake form is working as intended before we transition off of the previous Airtable process.

**A user should be able to:**
- Follow a link to the form from reporstream.cdc.gov
- Be able to view the ELR documentation if they need to review
- Fill out & submit the form 
- If any errors, form should give helpful validation alerts/info
- Get a confirmation email on submission

**We should be able to:**
- Get error-free submissions
- Have records show up in the right place
- Be able to follow-up/take action quickly after submissions

**Comment by anshulkumar-usds** [comment]
Update 5/10: Checking with Mary Peck in CDC about getting admin perms to Dynamics

**Comment by anshulkumar-usds** [comment]
Form is now available in production and meets the above states AC: https://prime.powerappsportals.us/siw/
