### ISSUE TITLE
Discussion items for ReportStream May 10 1pm ET Dev Sync

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-data-hub#1040]
@tlosbo
@mauricereeves 
@Mr0grog 
@mry-usds 
@RickHawesUSDS 
@ronaldheft-usds 
@carlosfelix2 
@joemeree 

Submit your topics here.

**Comment by MauriceReeves-usds** [comment]
My only issue is: https://app.zenhub.com/workspaces/prime-data-hub-5ff4833beb3e08001a4cacae/issues/cdcgov/prime-data-hub/1041

**Comment by MauriceReeves-usds** [comment]
One more. We are starting to get the issues from dependabot for security risks. We need to come up with a strategy to deal with these and figure out how these affects our ATO. 

https://github.com/CDCgov/prime-data-hub/security/dependabot

**Comment by jimduff-usds** [comment]
Meeting notes:

- Security:  @MauriceReeves-usds 's question Regarding the currently unfixable vulnerability: @mry-usds will add a zen hub ticket tracking the issue, and will notify eleventy of the issue, and track it.    Label our zen hub ticket with a  'security' label.   Add security review as a regular item at tech sync.
- Good discussion regarding @MauriceReeves-usds's question on NJ - he'll reach out to NJ to request conform to HL7 standards; if not possible then a quick-turnaround solution is acceptable.  If someone would like to take on a long-term rebuild of the way we handle valuesets, let @jimduff-usds know.
- @carlosfelix2 asked about how we decide when to do ad-hoc/ one-off work or not.   We try to meet states where they are, and we are also actively working to improve the overall public health data ecosystem, which includes standardization - these two goals can be in conflict at times.
- @tlosbo brought up question of release notes procedure.   Need a formal mechanism to communicate changes out to both Senders and Receivers.
