### ISSUE TITLE
Engineering issues for May 17

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-data-hub#1098]

**Comment by jimduff-usds** [comment]
Add your discussion items below.
@tlosbo
@mauricereeves
@Mr0grog
@mry-usds
@RickHawesUSDS
@ronaldheft-usds
@carlosfelix2
@joemeree

**Comment by MauriceReeves-usds** [comment]
Something I worked on over the weekend was adding fluent assertions to the project in a branch to make unit tests easier to read and more...well..."fluent." I would like to give a quick demo of what that looks like and if there's interest I'll convert over the rest of the unit tests.

**Comment by ronaldheft-usds** [comment]
I can give an overview of the zero-downtime deployment work I've done here: https://github.com/CDCgov/prime-data-hub/pull/1064
