### ISSUE TITLE
TX HL7 schema

### ISSUE THREAD

**Issue by RickHawesUSDS** [CDCgov/prime-data-hub#146]
The TX PHD would like to receive ELR in HL7 format. 

**Background**
https://www.dshs.state.tx.us/IDCU/investigation/ELR/Texas-HL7-2_5_1-ELR_Specification_-2016_Final-Draft-4-29-16.pdf

**Acceptance Criteria**
- [ ] Schema that follows the ELR specification
- [ ] Kayode Olupinyo of TX PHD reviews

**Comment by drew-usds** [comment]
Waiting on feedback.
