### ISSUE TITLE
Test the merge step

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-data-hub#165]
Tickets #162 and #164 do a pretty good job of testing `reports`, `translate` steps, and partially testing `send` step.

This ticket is to write something that tests `merge`

1.  Create 3 small fake data files in the simple report schema.  Find and save the primary keys from each file.
2.   Call merging (I'm assuming there's a programmatic way to do this directly in Kotlin.  If not, will need to write it.
3.   Merge and assert that all the primary keys in the original 3 data files are in the merged file.

I think there's no need to write out the merged file (?)

**Comment by jimduff-usds** [comment]
Note:  as part of this, I added a --merge option to the CLI.  Its getting a bit messy.  

@Mr0grog , rick tells me you might do some cleanup in main.kt?      My tweaks are in jim/fixes2 branch at the moment, not merged in yet.

**Comment by Mr0grog** [comment]
> Its getting a bit messy.

👍 I had a similar thought! I’m taking a look at splitting it up into separate commands (process data, list schemas, generate docs) to clarify that these are mutually exclusive operations and make it a little easier to see what options apply where. Maybe I can add a little more explanation to the help text while doing so. Hoping this might help me grok the structure of things a little more, too.

**Comment by jimduff-usds** [comment]
> > Its getting a bit messy.
> 
> 👍 I had a similar thought! I’m taking a look at splitting it up into separate commands (process data, list schemas, generate docs) to clarify that these are mutually exclusive operations and make it a little easier to see what options apply where. Maybe I can add a little more explanation to the help text while doing so. Hoping this might help me grok the structure of things a little more, too.

That would be awesome!   `prime` is ready to grow up to become a _real_ cli.  ;) 

Note that Mo (@mauricereeves ) also has some incoming additions to the cli, adding an ability to do fancy comparisons of two csv files.  They are in a PR at the moment.

**Comment by RickHawesUSDS** [comment]
I think this would be a good first issue. Putting back into the backlog.
