### ISSUE TITLE
Accept Traffic via prime.cdc.gov

### ISSUE THREAD

**Issue by cglodosky** [CDCgov/prime-data-hub#183]
To standardize the way in which clients interact with the data hub, we want to implement a `prime.cdc.gov` endpoint.  

Acceptance Criteria:
[ ] Clients route to `prime.cdc.gov`
[ ] Certificate management and rotation
[ ] Traffic routed via Front Door

**Comment by RickHawesUSDS** [comment]
Closing because of the Akamai epic.
