### ISSUE TITLE
Test:  end2end from PDI --> AZ

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-data-hub#25]
Write end-to-end test cases that represent our initial use case - starting from Prime Data Input (PDI) data, and transforming it into the format Arizona's Public Health Dept (PDH) wants to receive.

See this prime-central ticket for info on the formats:   https://github.com/CDCgov/prime-central/issues/84

**Comment by RickHawesUSDS** [comment]
I have sample Mirth Instances in docker containers which could be used to simulate the AZ department.

**Comment by drew-usds** [comment]
Duplicate.
