### ISSUE TITLE
Improve synthetic data generation

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-data-hub#311]
To be updated by @MauriceReeves-usds

**Comment by jimduff-usds** [comment]
Something to think about:  Our current fake data generator walks thru all the values in the various value sets - which is very valuable in creating data that is good for testing the full domain of possible inputs.

So maybe we have a "Generate good test data" setting and a separate "Generate realistic real-world data" - which tends to be far less diverse.

**Comment by MauriceReeves-usds** [comment]
@jimduff-usds - agreed. I discussed this with @RickHawesUSDS and @jlusds. When I create the quasi-real data out of actual data, that will work for "realistic test data," and then we will have a more robust edge case data with many different potential values per column.
