### ISSUE TITLE
Schemas appear to be cross contaminating

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-data-hub#323]
### Description
When running `quick-test.sh` to import the PDI schema, I noticed that it was attempting to decode values for `patient_gender` according to the FL schema alt values. It was also trying to use the `$code` format even though the PDI schema does not specify using this format. This was causing errors in importing PDI data back into Hub.

I was able to confirm this by removing the altValues from `patient_gender` in the FL schema and then reran `quick-test.sh` and it completed successfully.

### Examples
![Screen Shot 2021-01-15 at 12.47.41 PM.png](https://images.zenhubusercontent.com/5ff4880376fe251547594b05/41a6e84b-ef67-46d8-b19b-c428ecc34f0a)

![Screen Shot 2021-01-15 at 12.47.55 PM.png](https://images.zenhubusercontent.com/5ff4880376fe251547594b05/97ca9309-28d3-463a-ad88-2e85273fa5d1)

If you see above, the field is checking alt values first, but according to the spec for PDI, there's no altValues assigned to this element.
![Screen Shot 2021-01-15 at 12.51.41 PM.png](https://images.zenhubusercontent.com/5ff4880376fe251547594b05/69e94427-4978-4f16-b6de-0dc6567c73d6)

### Analysis
For the case of the PDI schema, it does not seem like it should have either the `altValues` or the `$code` format specified.

cc: @jimduff-usds @RickHawesUSDS

**Comment by jimduff-usds** [comment]
Just re-an quick-test in the Fake_Data_Improvements branch - not seeing any exceptions now.

Also tested generating PDI data in FL, then routing that to FL output schema:
```
./prime data --target-state FL --input-schema primedatainput/pdi-covid-19 --input-fake 100 --output-dir junk/
./prime data --route --output-dir ./junk --input ./junk/pdi-covid-19-7a805b97-b607-42ae-8551-a5e6d1758099-20210125124719.csv --route --input-schema primedatainput/pdi-covid-19 
```

which also worked.
