### ISSUE TITLE
Naming: ongoing disucssion & :fingers-crossed: final selection

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-data-hub#340]

**Comment by jimduff-usds** [comment]
Synonyms for 'hub' from thesaurus.com:   core, focus, heart, center.  I really like '**heart**' - nice feel, perfect metaphor, and with the health focus too.
- HeartLink
- HeartNet
- HeartBridge. (could abbreviate to HB, which everyone will pronounce as 'hub')
- HeartHub
- HeartBase (HB, too)

Health is an option too, although less memorable:
- HealthNet
- HealthLink
- HealthBridge
- HealthHub
- HealthBase

**Comment by drew-usds** [comment]
Asked partners for examples of what comes to mind when thinking of our work together:

> ... when I think of the whole project ...
> - Efficient
>- Progressive
> - Secure
> - Collaboration
> - Game Changer (for public health and the facilities)
> - Time saver
> - Accurate, timely data
> - Increased ability to respond to crisis
> - Creating linkage (between the facility and county, state and county, state and facility, like chain links connecting all of us)

>  TBD from 2nd partner

**Comment by drew-usds** [comment]
From 1/21 meeting with Alex and Raymond:

- [ ] Put together suggestions that meet three different "tiers"
  - Very specific name ex: "router"
  - More broad name ex: "connector"
  - Very high level ex: "hub"
- [ ] Create form in Teams to get feedback on three suggestions from CDC SMEs
  - Use a rating scale for options, not just y/n

**Comment by drew-usds** [comment]
Survey sent out to list of CDC SMEs provided by Alex.

https://forms.microsoft.com/Pages/ResponsePage.aspx?id=aQjnnNtg_USr6NJ2cHf8j_-2JElpe3ZDi-rvSX1_npVUQlQzWjMzRzdYQktGTU1HNU5VRldJUUY5TC4u

**Comment by jlusds** [comment]
Wohooo! Thanks drew

**Comment by drew-usds** [comment]
Final additions to survey results went out last week. Waiting to hear feedback from Alex.

**Comment by jlusds** [comment]
Name confirmed as ReportStream
