### ISSUE TITLE
address useful hl7 feedback from AZ PHD

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-data-hub#347]
Comments from AZ in email, 1/20/2021: regarding issues found in hl7 data:

FHS/BHS
Header information doesn't make sense. Looks like it's missing a File/Batch Sending Facility value.

MSH4, ORC21
It would be nice if this value matched what you were sending in the flat file.
HL7-Sierra Vista Canyons
Flat File-Via Elegante, Sierra Vista Canyons

OBR3
This is where we primarily look for the Accession number. It looks like you are populating OBR2 with that ID, could you also populate OBR3 with that same ID?

OBX17
It would be nice to have a human readable value in this field instead of the ID. Below is an example of how others are populating this field. We could make the ID work if necessary. 
What is currently being populated: 10811877011290_DIT^^99ELR
What others are populating in this field: BinaxNOW COVID-19 Ag Card_Abbott Diagnostics Scarborough, Inc._EUA_Abbot_EUA^^99ELR

**Comment by jlusds** [comment]
This was done

**Comment by jimduff-usds** [comment]
To be clear, I have not yet done any work on this.  Did @mauricereeves ?

**Comment by MauriceReeves-usds** [comment]
@jimduff-usds - I have addressed issues with the MSH, FHS, and BHS segments.

For OBR-3 we won't be sending the Accession number, and we are currently going to send the Message ID instead of any other value. I don't know if that's going to be acceptable to AZ or not. I can discuss with them if that would help clarify.

OBX-17 is sending through the value that they want now.

**Comment by jlusds** [comment]
Sorry I closed this by accident, but coincidentally was revisiting this just now!

@MauriceReeves-usds I'll add you to the thread. I like the idea of proposing that we send the Message ID

**Comment by jimduff-usds** [comment]
@mauricereeves , Dunno if this is possible, but it would be a nice win if we passed the message_id to all downstream hl7 schemas (and we'd also need to make sure its mentioned as the "trackingElement" for each schema)

This would be a good thing because the item lineage code attempts to grab trackingElement actual values and store them in the audit/lineage tables, since they are a value the external users would be able to refer to.  However, this hasn't worked well for hl7 and redox.  I think at the moment, few or none of these schemas have any trackingElement defined. 

Strangely, the AZ HL7 schema has message_id as the trackingElement, but then never contains message_id!    I suspect this is a mistake on my part from when I set it up.  But it should throw an error in our Schema.kt code.

Jim

**Comment by MauriceReeves-usds** [comment]
@jimduff-usds it's definitely possible. Right now we send it as the specimen ID and OBR-3. We could add it to the NTE section as well if you want some custom place to put it that we could refer back to, but for now I think having it in SPM-2 should be sufficient.
