### ISSUE TITLE
First round of user feedback on web receiver experience

### ISSUE THREAD

**Issue by jlusds** [CDCgov/prime-data-hub#403]
Talk to 3 PHDs

**Comment by drew-usds** [comment]
Research plan from Celeste: https://docs.google.com/document/d/1mmqRvviiiwkcqjdlaZPRukaAE4pP4AAJqr_yK9_9o4Y/edit?usp=sharing

**Comment by drew-usds** [comment]
Research schedule:

- [x] Teresa Jue - CDC - 2/18
- [x] Sara Johnston - CDC - 2/19
- [ ] Kat Davis - AZ - 2/23
- [ ] Allison C - FL - TBD
- [ ] ?? - LA - TBD
- [ ] ?? - PA - TBD

**Comment by drew-usds** [comment]
**Overall findings reported out on Sprint 11 Demo Day:**

https://docs.google.com/presentation/d/18mrd-mL-ZKPqcIggcbE_SNLH3STPDnPTDmUaiz8klno/edit?usp=sharing

**Raw notes for reference:**

https://docs.google.com/spreadsheets/d/1FhZAvgTXtuPUYA6_gJM3XFkp5bALLWKF-RblFwgKwMc/edit?usp=sharing
