### ISSUE TITLE
Broken CDC logo image on Okta login

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-data-hub#410]
I'm not able to see the CDC logo image on the Okta login page. Seems to work on other Mac browsers and all Win browsers as well.

- MacOS
- Chrome 87.0.4280.141

<img src="https://images.zenhubusercontent.com/5ff50e49f74e134e95117280/10d6ec73-6725-4da9-a633-c6a34e76cfa9" width="400" />

**Comment by mry-usds** [comment]
Unable to replicate - will monitor
