### ISSUE TITLE
Weekly Dev Sync: Feb 8, 2021

### ISSUE THREAD

**Issue by ronaldheft-usds** [CDCgov/prime-data-hub#461]
Weekly topic proposal thread. Add your topic proposals as comments in this GitHub issue.

**Comment by ronaldheft-usds** [comment]
I can do a walkthrough of my PR for application secrets: https://github.com/CDCgov/prime-data-hub/pull/392

I can show off the CLI and give a high-level overview of how it works. Is there anything specific anyone would like to see?

**Comment by RickHawesUSDS** [comment]
Thinking about my testing problems, maybe an end-to-end testing check list would be helpful.
