### ISSUE TITLE
Add names from other cultures in fake data output

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-data-hub#487]
We should add in logic in fake data to output a small sample of names and addresses in other cultures:
- Simplified Chinese
- Mexican Spanish
- Canadian French
- Vietnamese
- Hindi

This way we can verify that names, emails, etc with unicode characters in them can still be serialized into different formats

**Comment by MauriceReeves-usds** [comment]
As part of our testing and preparing for wider adoption across the US, we should create a set of tests with names in non ASCII/non EN-US format to make sure CSV serialization and HL7 serialization doesn't break.

**Comment by carlosfelix2** [comment]
Default character sets:
Windows: Windows-1252 (1 byte)
MAC: UTF-8
Dev Docker container in Windows - US-ASCII
Dev Docker container in MAC - ????
Azure deployment - ?
