### ISSUE TITLE
ReportStream.cdc.gov domain

### ISSUE THREAD

**Issue by RickHawesUSDS** [CDCgov/prime-data-hub#567]
Connect w/ Michael Crawley

**Comment by drew-usds** [comment]
Messaged Michael about first steps on 3/15.

**Comment by drew-usds** [comment]
As of 3/24, following subdomains have been set up with help from CDC AD help desk:

- [x] reportstream.cdc.gov 
- [x] staging.reportstream.cdc.gov
- [x] test.reportstream.cdc.gov

Waiting for everything to replicate! Kudos @cglodosky !
