### ISSUE TITLE
Who are our next set of senders? Who are we talking with next?

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-data-hub#59]
- Possibly TX, because of HL7
- Possibly FL

**Comment by jlusds** [comment]
**Pilot states**
Arizona
Florida
Texas
**Ready leads**
Colorado
Pennsylvania
**HCA Tier 1**
Kentucky
Missouri
**HCA Tier 2**
New Hampshire
South Carolina
Tennessee
**Warm leads**
Washington
North Carolina
North Dakota
Connecticut
