### ISSUE TITLE
Design "new results ready" experience

### ISSUE THREAD

**Issue by jlusds** [CDCgov/prime-data-hub#60]
We plan to send jurisdictions a notification everyday with a link to download results for the last 24 hours. This will be accessible for ~30 days

Design the email experience and content

Related to #91

**Comment by drew-usds** [comment]
Email mockup on Figma:

https://www.figma.com/file/VrSkTA87t8PPeXPugQ0i8O/Download-site?node-id=0%3A1

**Comment by drew-usds** [comment]
Added draft HTML to `email-templates` branch:
https://github.com/CDCgov/prime-data-hub/tree/email-template
