### ISSUE TITLE
Extract data schema from code into content so we can publicly share

### ISSUE THREAD

**Issue by jlusds** [CDCgov/prime-data-hub#61]
Currently we have our "receive" requirements in code. We want to be able to share this with potential partners (e.g. vendors who are working with data automation team and need to convert ELR data into a format we can accept).

Task = create a human readable 'how to' to describe the fields required to connect with Data Hub

Content = https://github.com/CDCgov/prime-data-hub/issues/76

**Comment by jlusds** [comment]
@RickHawesUSDS  this is the task we discussed today. Please let me know if this is scoped to what we discussed.

**Comment by drew-usds** [comment]
Maurice to help when onboarded with org
