### ISSUE TITLE
Spec out eng requirements for 3rd party vendor (e.g. Redox)

### ISSUE THREAD

**Issue by jlusds** [CDCgov/prime-data-hub#63]
https://developer.redoxengine.com/ is the overview doc, https://developer.redoxengine.com/data-models/Results.html is the results specific portion that I think we'd use

Figure out what we need to do to 1) integrate with Redox, 2) send data through to states

**Comment by jimduff-usds** [comment]
Completed field-by-field comparison of Redox expected with our SimpleReport fields.   Meeting with Redox, then will document eng reqs.  not done.
