### ISSUE TITLE
Alert on HealthCheck failures

### ISSUE THREAD

**Issue by RickHawesUSDS** [CDCgov/prime-data-hub#654]
Make healthcheck work on our function apps. Not for website. 

**AC**
- [ ] Complete Healthcheck function with tests for DB up and some logic for SFTP up
- [ ] Healthcheck is enabled in Function App
- [ ] Healthcheck does not fail for partial failures like single SFTP failures
- [ ] Verify healthcheck failure will raise an alert

**Comment by jimduff-usds** [comment]
@RickHawesUSDS, are you picturing something that runs once a day (or whatever), and checks every sftp connection, and the database?

It could collect the list of errors, then throw a single exception listing all the problems, which could then trigger a PagerDuty alert.  

Is that what you are looking for?

**Comment by jimduff-usds** [comment]
@cglodosky, turning this over to you.    There is already an `api/check?sftpcheck=all` implemented, currently just returning human readable text, but could be modified easily to return a structured response, if that's useful.

Also, the `api/reports?option=CheckConnections` call will both act as a HealthCheck of the reports api, and the database connectivity too, if that's useful.

Jim

**Comment by ronaldheft-usds** [comment]
Duplicate of CDCGov/prime-devops#6
