### ISSUE TITLE
Add Secrets for GU, VT, and NM

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-data-hub#712]
Login information is posted in KeyBase for GU, VT, and NM. These values need to be added to the credentials we're storing in prod.

**Comment by ronaldheft-usds** [comment]
Working on now.

**Comment by ronaldheft-usds** [comment]
Done. @cglodosky please verify.

**Comment by cglodosky** [comment]
Production values look good, but I'm not seeing any in staging.  Do we need them added there as well?
