### ISSUE TITLE
Get monitoring with alerts working.

### ISSUE THREAD

**Issue by RickHawesUSDS** [CDCgov/prime-data-hub#73]
To be able to quickly detect when an issue arises in production, we need monitoring and alerting setup. 

Suggested Approach
- Use Azure infrastructure to get something working quickly
- Consider other options in the long term

Acceptance Criteria
- monitoring of inflows and outflows from the hub to catch interruptions
- monitoring of resource consumption to catch leaks
- Decided on alerting levels
- Alerts

**Comment by drew-usds** [comment]
Broke out into individual issues.
