### ISSUE TITLE
Move AZ facilities from Test to Prod

### ISSUE THREAD

**Issue by jlusds** [CDCgov/prime-data-hub#772]
The following facilities have been approved:

Tucson Unified School District,Tucson Unified Sch
Sister Jose Women's Center,Sister Jose Women's Ce
Vail School District,Mica Mountain High School
Tucson Waldorf School,Tucson Waldorf School
Vail School District,Vail Theatre of the Arts (VT
Recovery in Motion Treatment Center,Recovery in M

**Comment by jlusds** [comment]
@MauriceReeves-usds this is a state operations task that Jim worked on in the past for AZ

**Comment by jimduff-usds** [comment]
Bleh.   The use of matches and doesNotMatch were written to cover this case, but this was meant to be short-term until simple report implemented the processing_mode_code.
Currently we have, for example:  
`"doesNotMatch(ordering_facility_name,Tucson Mountains,Tucson Foothills,Sierra Vista Canyons)"`
in the AZ test receivers, and
`"matches(ordering_facility_name,Tucson Mountains,Tucson Foothills,Sierra Vista Canyons)"`
in the elr-prod receiver.

This isn't scalable.  Certainly, we can and probably should add these additional facilities to the burgeoning list, but ultimately this needs to be a setting done by the facility themselves, by an administrative UI switch inside SimpleReport, that then sets the processing_mode_code in the data. That is a scalable solution.

**Comment by jlusds** [comment]
Thanks for the feedback. I followed up with AZ if there's a more sustainable solution.
________________________________

**Comment by jimduff-usds** [comment]
Closing.  We resolved this by getting AZ to stop doing this.  Issue still lurking out there for other states, tho.
