### ISSUE TITLE
Service level agreement

### ISSUE THREAD

**Issue by RickHawesUSDS** [CDCgov/prime-data-hub#78]
- How can we best support? Holidays, etc?
- How will we get feedback? (ex: problems with input app)

**Comment by drew-usds** [comment]
Based on brief talks with AZ, we'll go with this process to start and modify as needed.

**Support process:**

- Partners will contact us via email at `support@prime.cdc.gov` (see #201)
- Support inbox will be monitored during normal sending hours on days when data is being sent. 
  - Sending hours are times we're scheduled to send data to partners, TBD.
  - Changes to support hours (ex: holidays) will be communicated to partners (maybe an auto responder?)
- Hub team will rotate being on call for monitoring the support inbox.
- Monitoring team will turn emails into GitHub tickets using a support issue template.
  - Tickets will have a support label.
  - Tickets will have an engineer assigned.

**Things we won't do:**

- Provide phone support

**To do:**

- [ ] Create support issue template in GitHub
- [ ] Assign support rotation
