### ISSUE TITLE
What is your topic for today's ReportStream Engineering Sync?

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-data-hub#787]
Feel free to leave a comment with your topic / agenda item here

**Comment by jimduff-usds** [comment]
A couple items for discussion

- Azure retries on Azure Function failures, vs our retries.  The 'timeout' exceptions we've seen are both caught by our retry mechanism and also by Azure's built in retry mechanism - so the task gets retried **twice**, simultaneously.  Its not clear if this is causing bugs.   The question is whether we should use Azure's built in exponential backoff retry mechanism, rather than our home-built version.

- Scaling:    Ron and I have been assuming the database (and hence, the database connection pool) is the limiting factor in our ability to scale to arbitrarily large processing numbers.   Is that an accurate assumption?   If so, does that imply we compartmentalize functionality of one set of ReportFunction/BatchFunction/SendFunction/postgresDb/blobStore as a single "ReportStream Engine"?  
Then the scaling questions is:
1. how can we maximize the number of Reports/Items processed by one Engine, and
2. how can we scale to multiple engines

- Discussion of PII if we begin to pull location, facility, and positivity data into the database.

**Comment by carlosfelix2** [comment]
I have a TPCA meeting at 1pm and will miss the beginning of this meeting.  Will join in as soon as I can.
