### ISSUE TITLE
Actually send test data to AZ + PIMA

### ISSUE THREAD

**Issue by RickHawesUSDS** [CDCgov/prime-data-hub#80]
- [X] Get an SFT account setup with AZ 
- [X] Get a list of email addresses to send to Pima
- [ ] Schedule time with each to verify receipts

Linked issues

Go live for Pima - https://github.com/CDCgov/prime-data-hub/issues/89
Go live for AZ - https://github.com/CDCgov/prime-data-hub/issues/47

**Comment by jlusds** [comment]
11/18 update - awaiting update from Pima to get sign off on format/addresses. They promised answer by Friday 11/20

**Comment by drew-usds** [comment]
Closing, duplicated in above go live checklists.
