### ISSUE TITLE
V. detailed map across products @ drew

### ISSUE THREAD

**Issue by RickHawesUSDS** [CDCgov/prime-data-hub#81]
- Where does it all connect?
- Where are gaps?
- What does [partner] expect from us?
- How can we respond quickly to problems? How can we provide support?

**Comment by drew-usds** [comment]
Working from this Mural link, starting in earnest _today!_

https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1605258729922/0aade9009ec1ad1e4db68edc4e2e3f8cb95f48df
