### ISSUE TITLE
Develop plan for user agreements needed to launch and scale

### ISSUE THREAD

**Issue by RickHawesUSDS** [CDCgov/prime-data-hub#82]
Establish process and documents needed to scale to
-More states
-More senders (outside of USDS/CDC senders), like HCA

**Comment by jlusds** [comment]
Next conversation on Monday 11/23

**Comment by drew-usds** [comment]
Sprint planning updates:

- State reporting side, data use agreement at sender level was fine
- Setting up operational processes (paperwork, etc)
- Need to restart HCA conversation
