### ISSUE TITLE
Agenda items for April 19 Dev Sync

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-data-hub#842]
Post your agenda items here!

**Comment by jimduff-usds** [comment]
@Mr0grog @mauricereeves @joemeree @carlosfelix2 @mry-usds @RickHawesUSDS @ronaldheft-usds 
Post agenda items here

**Comment by MauriceReeves-usds** [comment]
As we onboard more people to help with senders and receivers, I'd like us to talk about using staging to send test files to states for them to review, rather than manually uploading or emailing them. I think that would mean in staging we'd need to set up some kind of dev sender.
