### ISSUE TITLE
Discussion items for today's April 26 ReportStream Dev Sync

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-data-hub#937]
@Mr0grog @mauricereeves @joemeree @carlosfelix2 @mry-usds @RickHawesUSDS @ronaldheft-usds
Post agenda items here

**Comment by joemeree** [comment]
Testing the new Oracle WATERS API (connection, WATERS schema, error handling)

**Comment by RickHawesUSDS** [comment]
@carlosfelix2 Move to Gradle

**Comment by RickHawesUSDS** [comment]
Mail function idea
