### ISSUE TITLE
Create SendGrid accounts for team

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-data-hub#949]
### Needs an account

- [ ] Anshul
- [x] Drew
- [x] James
- [ ] Jim
- [x] Matt
- [ ] Rick
- [ ] Ron

**Comment by drew-usds** [comment]
@jlusds you, Matt, and I have accounts now ... do other folks on the team need them as well, or should I close this one out?

**Comment by jlusds** [comment]
Looks good I think!
