### ISSUE TITLE
Discussion items for May 3 Developer Sync

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-data-hub#986]
@RickHawesUSDS @Mr0grog @mauricereeves @mry-usds @carlosfelix2 @ronaldheft-usds @joemeree @submit Agenda items as desired!

**Comment by ronaldheft-usds** [comment]
Discuss Palo Alto firewall test / production plan.

* Scheduled test with Palo Alto team
  * We need to simulate SFTP / API traffic in Ron's Azure dev environment to validate the Palo Alto is functioning correctly
  * What do we need to do to prepare and when can we schedule this test
* Roll out
  * All environments will need to be migrated to a new CDC-controlled VNET
  * Out existing resource groups will be okay
  * Migration is actually not too bad from a Terraform perspective, needs more planning to minimize outage window
* Caveats
  * The new VNET will remove our VPN and I haven't asked yet, but I doubt we will get the firewall rules approved to allow VPN ingress
    * CDC's VPN choice is CyberArk and we should use it
  * Firewall rules are added by port / IP
    * This means every site we connect to will need a firewall rule request
    * Palo Alto team is commiting to a 1 week turnaround time or less on new firewall rules, we need to make this part of our onboarding process
    * If firewall rules become onerous, Palo Alto team is open to explore alternative processes for rule approval

**Comment by carlosfelix2** [comment]
Discuss if schema documentation HTML will exist with the markup files (both at the same time).  Looks to me that having both will be useful.  Re: https://github.com/CDCgov/prime-data-hub/pull/985

Depending on the above, Sonar flags the HTML as duplicate code.

**Comment by joemeree** [comment]
Ron, It's not clear if this affects the WATERS to ReportStream interface

 

Joe Meree  AI Architect  DataRobot  cell:703-967-4730
***@***.***> ***@***.***
